CREATE DATABASE

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) UNIQUE NOT NULL
)

CREATE TABLE videojuegos (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    genero VARCHAR(100) NULL,
    plataforma VARCHAR(100) NULL,
    fecha_lanzamiento DATE NULL,
    precio DECIMAL(10, 2) NULL,
    jugado BOOLEAN NOT NULL DEFAULT FALSE
)